; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ${PROJECT_DIR}

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103R8
framework = libopencm3
upload_protocol = cmsis-dap
;debug_tool = stlink
debug_tool = cmsis-dap
build_flags =
  -I FreeRTOS-Kernel/include
  -I FreeRTOS-Kernel/portable/GCC/ARM_CM3
  -D STM32F103xB
  -D COLOR_LOG
  -Og
